# Location where configuration files will be stored. It is usually '/home/pi'
config_dir: "/home/username"

# This allows 'pi' user to SSH to raspberry4 without password
pi_ssh_authorized_keys: https://github.com/dhlavaty.keys

pihole_enable: false
pihole_password: "abc123"

# netatmo2mqtt settings - see https://github.com/dhlavaty/netatmo2mqtt
#
# You can get yours from https://dev.netatmo.com/apps/
# AWARE: You need to set `read_thermostat` topic when generating your tokens.
netatmo2mqtt_oauth_client_id: ""
netatmo2mqtt_oauth_client_secret: ""
netatmo2mqtt_oauth_client_refresh_token: ""

backup_enable: false
backup_dir: "/home/pi/subdir-to-backup/"
backup_google_project_id: "google-project-id"
backup_google_bucket: "google-bucket-name"
backup_google_service_account_key_json: "subdir/service-account-key.json"
backup_restic_password: "abc123"

homeautomation_enable: false

auto_reboot_disable: false
