- name: Backup homedir
  # Blocks create logical groups of tasks. Blocks also offer ways to handle task errors,
  # similar to exception handling in many programming languages.
  block:
    - name: Install Restic
      become: true
      # Manages apt-packages
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
      ansible.builtin.apt:
        name: restic
        state: present
      tags:
        - backup

    - name: Create directory structure for backup scripts
      # Manage files and file properties
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
      ansible.builtin.file:
        path: "{{ config_dir }}/backup"
        state: directory
        mode: 0755
      tags:
        - backup

    - name: Copy service-account key JSON file
      # Copy files to remote locations
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      ansible.builtin.copy:
        src: "{{ backup_google_service_account_key_json }}"
        dest: "{{ config_dir }}/backup/service-account-key.json"
        mode: "0640"
      tags:
        - backup

    - name: Copy backup shell script (dot-env.j2)
      # Template a file out to a target host
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
      ansible.builtin.template:
        src: dot-env.j2
        dest: "{{ config_dir }}/backup/.env"
        mode: "0640"
      become: true # we want .env to be accessible only by root
      tags:
        - backup

    - name: Copy backup shell script (restic-ls.sh.j2)
      # Template a file out to a target host
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
      ansible.builtin.template:
        src: restic-ls.sh.j2
        dest: "{{ config_dir }}/backup/restic-ls.sh"
        mode: "0750"
      become: true # we want .env to be accessible only by root

    - name: Run Restic backup
      # Execute commands on targets
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
      ansible.builtin.command: '/usr/bin/restic --repo gs:{{ backup_google_bucket }}:/ backup {{ backup_dir }} --verbose --exclude="node_modules" --exclude=".git" --exclude=".npm"'
      args:
        chdir: "{{ backup_dir }}"
      environment:
        - GOOGLE_PROJECT_ID: "{{ backup_google_project_id }}"
        - GOOGLE_APPLICATION_CREDENTIALS: "/home/pi/backup/service-account-key.json"
        - RESTIC_PASSWORD: "{{ backup_restic_password }}"
      become: true
      changed_when: false
      tags:
        - backup
