# PIHOLE
- name: Install nslookup
  become: true
  # Manages apt-packages
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  ansible.builtin.apt:
    name: dnsutils
    state: present

- name: Create directory structure for pihole-v6
  # Manage files and file properties
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: "{{ config_dir }}/docker/pihole-v6"
    state: directory
    mode: 0755

- name: Copy docker-compose-pihole-v6.yaml (as Template)
  # Template a file out to a target host
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
  ansible.builtin.template:
    src: docker-compose-pihole-v6.yaml
    dest: "{{ config_dir }}/docker/pihole-v6/docker-compose.yaml"
    mode: "0640"

- name: Ensure pihole-v6 is running (IF pihole_enable == true)
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/pihole-v6/"
    build: false
  become: false
  when: pihole_enable

- name: Ensure pihole-v6 is not running (IF pihole_enable == false)
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/pihole-v6/"
    state: absent
  become: false
  when: pihole_enable == false
